### ISSUE TITLE
trouble with running of main.py

### ISSUE THREAD

**Issue by okunahe** [coffee-cup/uvic-data-mining-mbti#1]
Hi everyone! 

I'm getting this error by running of main.py: 

Traceback (most recent call last):
  File "main.py", line 14, in <module>
    embedding_data = word2vec(config, code=ALL)
  File "/home/olya/env/personality-detection-master/mbti-master/word2vec.py", line 169, in word2vec
    embedding_data = get_one_hot_data(embedding_data)
  File "/home/olya/env/personality-detection-master/mbti-master/word2vec.py", line 139, in get_one_hot_data
    Y = one_hot_encode_type(row[0])
  File "/home/olya/env/personality-detection-master/mbti-master/utils.py", line 28, in one_hot_encode_type
    i = personality_types.index(t)
ValueError: 'enfp intj moments sportscenter top ten plays pranks' is not in list

Do you know maybe what could be reason for that?

**Comment by changlulu123** [comment]
i have this problem too
